# A little bit modified file from:
# https://packaging.python.org/guides/supporting-windows-using-appveyor/

notifications:
  email: false

branches:
  only:
    #- master
    - 1.1

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
  # We need numpy and cython installed to build qmeq
  - "%PYTHON%\\python.exe -m pip install cython"
  - "%PYTHON%\\python.exe -m pip install numpy"
  - "scripts\\build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

build: off

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
    name: mywheels

deploy:
  release: 1.1
  description: 'QmeQ 1.1'
  provider: GitHub
  auth_token:
    secure: qH8xSyfc5b1pBf1bWprxtfcaI1wfD3d6PRznR5LDb7ZQN8nnZeCgjx9fopFSL+zf
  artifact: mywheels
  draft: false
  prerelease: false
  force_update: true
  on:
    # release from tag 1.1 only
    branch: 1.1
    # deploy on tag push only
    appveyor_repo_tag: true
